### ISSUE TITLE
Transparent PNG anti-aliasing algorithm

### ISSUE THREAD

**Issue by jordyno** [thomcc/equirect-to-cubemap-faces#15]
I noticed that the resulting 32-bit PNGs tend towards black/gray-matte anti-aliased edges.
For example:
![b_y7_x7](https://user-images.githubusercontent.com/32031745/31914005-5a752174-b849-11e7-8738-15f2e16f07ec.png)
Is there any way to smooth this out? I tried Panotour Pro's EQR to Cubefaces conversion and got the same results.
The [input file](http://powderia.com/testpoly.png) is all clean of edges of course.
Thank you!

**Comment by thomcc** [comment]
A different texture filtering algorithm could be used, right now it only supports nearest neighbor and bilinear. I think this would be a slight improvement at best though -- the equivalent of scaling something down and then up in photoshop when using one of their fancier filters (such as bicubic) -- you'd still have blurriness.

Short of vectorizing and computing the transform on the vector (which would effectively be completely different code from what this lib does), I don't think anything will be as crisp as what you start with.

Closing -- I don't think there's much I can do to help this case a lot.

**Comment by jordyno** [comment]
the only solution I have found so far is using input file that is 22500x11250px. The gray anti-alias is seen also there, but barely visible. In general, the lower the resolution of input file, the more gray anti-aliased edges.
(the above image was taken from tiled 4096px cubeface with the input file of 10000x5000px)

**Comment by jordyno** [comment]
thanks, good to know! I will stick with high res eqr files

**Comment by thomcc** [comment]
Try using "nearest" interpolation, it might have better effects for this case.

**Comment by jordyno** [comment]
It is definitely clean of gray with nearest:
![b_y7_x7](https://user-images.githubusercontent.com/32031745/31914928-f77268bc-b84c-11e7-8dcf-7f806b8cff3f.png)

Just for your (or someone else's) reference if you need it in the future:
bilinear when using 22500x11250px input (512px tile of 4096px face):
![b_y7_x7](https://user-images.githubusercontent.com/32031745/31915002-32d4af8c-b84d-11e7-9b6f-270c8476c3c2.png)
nearest when using 22500x11250px input (512px tile of 4096px face):
![b_y7_x7](https://user-images.githubusercontent.com/32031745/31915052-56fc15f8-b84d-11e7-9dc8-b6ec8e97d9aa.png)

I think I will go with bilinear anyway, but will have to stick to hires PNGs or SVG

**Comment by jordyno** [comment]
By the way, the blurriness was not the problem, but the gray anti-aliased edges as they pop out when placed on top of certain colorful JPGs

**Comment by thomcc** [comment]
Are your inputs alpha premultiplied?

**Comment by thomcc** [comment]
Either way it's either an option that probably should be supported, or a bug in the library.

**Comment by jordyno** [comment]
I guess they are not as they come straight from Adobe Fireworks CS6 which supports 32-bit PNGs only. Looked it up on adobe forum and even photoshop supports only straight color. It would be surprising if FW did otherwise.

**Comment by thomcc** [comment]
Canvas pixels are non-prmultiplied alpha, which I had forgotten.

I think I pushed a fix for this, reopen if it persists.

**Comment by jordyno** [comment]
Wow, it is perfect now! You are a genius Thom! Thank you!

**Comment by jordyno** [comment]
Just for the reference, the resulting tile from a lower-res (10000x5000px) PNG:
![b_y7_x7](https://user-images.githubusercontent.com/32031745/31940900-23c84d6e-b8c0-11e7-9c5a-cf4af82cdf6b.png)
