### ISSUE TITLE
export jpeg images

### ISSUE THREAD

**Issue by A-Kasaaian** [thomcc/equirect-to-cubemap-faces#17]
I want to import resulted images of your library to another library which requires jpeg file. It's my main question, is there a way to export JPEG images?

**Comment by A-Kasaaian** [comment]
it's the script I use to test files
```
var imageData = Uint8Array.from(atob(po.replace('data:image/png;base64,', '')), j => j.charCodeAt(0));
          var imageCorrupted = ((imageData[imageData.length - 1] === 217) && (imageData[imageData.length - 2] === 255));
```

**Comment by thomcc** [comment]
What makes you confident that that means it's corrupted? That just checks two components from the last pixels are equal to two hard-coded values.

Also, I don't exactly see what that example has to do with my library.

**Comment by A-Kasaaian** [comment]
Ummmm, yes you are right. Let me change the title and ask my main question.

**Comment by A-Kasaaian** [comment]
OK I could do that. There was nothing to do with the library.
